### ISSUE TITLE
уроки на украинском

### ISSUE THREAD

**Issue by savadanil** [chopikus/SchoolHelperSE#1]
начало и конец поменяны местами

**Comment by savadanil** [comment]
домашнее задание  
где дата  писать не 30.7.2017 а 30.07.2017

**Comment by savadanil** [comment]
убрать для создания группы зайдите в настройки

**Comment by savadanil** [comment]
уберите локальный режим дз

**Comment by chopikus** [comment]
Все уязвимости исправлені
